data class Post(
    internal var id: Int = 1,
    val ownerId: Int,
    val fromId: Int,
    val createdBy: Int,
    val date: Int,
    val text: String,
    val replyOwnerId: Int,
    val replyPostId: Int,
    val friendsOnly: Boolean,
    val comments: List<Comment>,
    val copyright: String,
    val likes: Int,
    val reposts: Post?,
    val views: Int,
    val postType: String,
    val attachments: List<Attachment>?,
    val signerId: Int,
    val canPin: Boolean,
    val canDelete: Boolean,
    val canEdit: Boolean,
    val isPinned: Boolean,
    val markedAsAds: Boolean,
    val isFavorite: Boolean,
    val postponedId: Int,
)
